<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A1715B_aqar" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql5032.smarterasp.net;Initial Catalog=DB_A1715B_aqar;Persist Security Info=True;User ID=DB_A1715B_aqar_admin" SettingsObjectName="Aqar.Engine.Properties.Settings" SettingsPropertyName="DB_A1715B_aqarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactForm" Member="ContactForms">
    <Type Name="ContactForm">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users_Role" Member="Users_Roles">
    <Type Name="Users_Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactUs" Member="ContactUs">
    <Type Name="ContactUs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="PhoneNo1" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="PhoneNo2" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="WhatsApp" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Viber" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Twitter" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="GooglePlus" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="LinkedIn" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Youtube" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Late" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Long" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractType" Member="ContractTypes">
    <Type Name="ContractType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Image360" Member="Image360s">
    <Type Name="Image360">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageBalacony" Member="ImageBalaconies">
    <Type Name="ImageBalacony">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageBathroom" Member="ImageBathrooms">
    <Type Name="ImageBathroom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageBedroom" Member="ImageBedrooms">
    <Type Name="ImageBedroom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageGarden" Member="ImageGardens">
    <Type Name="ImageGarden">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImagePool" Member="ImagePools">
    <Type Name="ImagePool">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageReception" Member="ImageReceptions">
    <Type Name="ImageReception">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMainImage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainMenuBackend" Member="MainMenuBackends">
    <Type Name="MainMenuBackend">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainMenuFrontend" Member="MainMenuFrontends">
    <Type Name="MainMenuFrontend">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhotoSession" Member="PhotoSessions">
    <Type Name="PhotoSession">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceAverage" Member="PriceAverages">
    <Type Name="PriceAverage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PriceFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DescriptionAr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AddressAr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoomsNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BathroomNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BedroomNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceptionNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Area" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Space" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lift" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Balacony" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Garden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Garage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pool" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AirCondtion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CurrencyKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Long" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Late" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ContractType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserInCharge" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAqarContract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsNotAqarContract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ContractDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyType" Member="PropertyTypes">
    <Type Name="PropertyType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyVeiwed" Member="PropertyVeiweds">
    <Type Name="PropertyVeiwed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MacAddress" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role" Member="Role1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SpaceAverage" Member="SpaceAverages">
    <Type Name="SpaceAverage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpaceFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SpaceTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Square" Member="Squares">
    <Type Name="Square">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubMenuBackend" Member="SubMenuBackends">
    <Type Name="SubMenuBackend">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentMenuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubMenuFrontend" Member="SubMenuFrontends">
    <Type Name="SubMenuFrontend">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="TitleAr" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentMenuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SystemUser" Member="SystemUsers">
    <Type Name="SystemUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNo1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Online" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UniqueId" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UserImage" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbCurrency" Member="TbCurrencies">
    <Type Name="TbCurrency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CurrencyKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopTenProperty" Member="TopTenProperties">
    <Type Name="TopTenProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserContact" Member="UserContacts">
    <Type Name="UserContact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WhatsApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Viber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserFavourite" Member="UserFavourites">
    <Type Name="UserFavourite">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuildingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRate" Member="UserRates">
    <Type Name="UserRate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>